apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kritis-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kritis-clusterrole
subjects:
- kind: ServiceAccount
  namespace: ${K8S_NAMESPACE}
  name: kritis
