apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
  name: kritis-clusterrole
  labels:
    # Add these permissions to the "edit" default role, so that "edit" can see our CRD.
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups: ["kritis.grafeas.io"]
  resources: ["*"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["validatingwebhookconfigurations"]
  verbs: ["*"]
