apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
    name: attestationauthorities.kritis.grafeas.io
    labels:
      app: kritis-validation-hook
spec:
    group: kritis.grafeas.io
    version: v1beta1
    scope: Namespaced
    names:
        plural: attestationauthorities
        singular: attestationauthority
        kind: AttestationAuthority
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
    name: genericattestationpolicies.kritis.grafeas.io
    labels:
      app: kritis-validation-hook
spec:
    group: kritis.grafeas.io
    version: v1beta1
    scope: Namespaced
    names:
        kind: GenericAttestationPolicy
        plural: genericattestationpolicies
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
    name: imagesecuritypolicies.kritis.grafeas.io
    labels:
      app: kritis-validation-hook
spec:
    group: kritis.grafeas.io
    version: v1beta1
    scope: Namespaced
    names:
        kind: ImageSecurityPolicy
        plural: imagesecuritypolicies
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kritisconfigs.kritis.grafeas.io
  labels:
      app: kritis-validation-hook
spec:
  group: kritis.grafeas.io
  version: v1beta1
  scope: Cluster
  names:
    kind: KritisConfig
    plural: kritisconfigs
    singular: kritisconfig
