apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: kritis-validation-hook
  labels:
    app: kritis-validation-hook
webhooks:
  - name: kritis-validation-hook.grafeas.io
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - pods
          - deployments
          - replicasets
    failurePolicy: Ignore
    namespaceSelector:
      matchExpressions:
      - {key: kritis-validation, operator: NotIn, values: [disabled]}
    clientConfig:
      service:
        name: kritis-validation-hook
        namespace: ${K8S_NAMESPACE}
      caBundle: ${K8S_CA_BUNDLE}
